### ISSUE TITLE
Problem while using Python's virtualenvs

### ISSUE THREAD

**Issue by tinylucid** [mgee/slimline#11]
Some very light virtualenv integration would be nice, is there any way to allow virtualenvs to display itself like in other prompts?

After I activate my virtualenv and go to the project folder I get this:

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/-----/-------/-------/-----/slimline/gitline/gitline.py", line 139, in _stashes
    self.repo.stashes = len(filter(bool, execute(['git', 'stash', 'list']).splitlines()))
TypeError: object of type 'filter' has no len()`

**Comment by mengelbrecht** [comment]
Slimline currently has no support for displaying virtualenv information. However, this should be not so hard to implement.

Regarding the exception you encountered, please try the latest master version. I just pushed a fix for it.

**Comment by tinylucid** [comment]
Now it works fine. Thank you! :)

**Comment by mengelbrecht** [comment]
Virtualenv support was added in #12 by @fgandellini
